#!/bin/sh
zenity --list \
--title "Proje" \
--width 1200 \
--height 700 \
--text "Lütfen 1'den 9'a kadar olan seçeneklerden birini seçiniz." \
--column="No" --column="Tanım" \
1 "Makine adını görüntüle" \
2 "İşlemci ve işlem birimleri hakkında bilgileri görüntüle" \
3 "Donanım listesini görüntüle" \
4 "Donanım bilgilerini görüntüle" \
5 "Pci veri yollarını ve bunlara bağlı cihazlarla ilgili ayrıntıları görüntüle" \
6 "Sabit sürücüler ve optik sürücüleri görüntüle" \
7 "Takılı dosya sistemlerini görüntüle" \
8 "Ayrıntılı donanım bilgilerini görüntüle" \
9 "USB detaylarını görüntüle" \
0 "Programdan çıkış" \

function projef
{
 echo ""
 echo -n "Devam etmek için ENTER tuşuna basınız."
 read
 clear
}

selection=
until [ "$secilen" = "0" ]; do
  zenity --info --no-wrap --text="Lütfen seçiminizi terminalden giriniz." \
  --width 400 \
  --height 200 \
  
 echo ""
 echo "Menü"
 echo "1-Makine adını görüntüle"
 echo "2-İşlemci ve işlem birimleri hakkında bilgileri görüntüle"
 echo "3-Donanım listesini görüntüle"
 echo "4-Donanım bilgilerini görüntüle"
 echo "5-Pci veri yollarını ve bunlara bağlı cihazlarla ilgili ayrıntıları görüntüle"
 echo "6-Sabit sürücüler ve optik sürücüleri görüntüle"
 echo "7-Takılı dosya sistemlerini görüntüle"
 echo "8-Ayrıntılı donanım bilgilerini görüntüle"
 echo "9-USB detaylarını görüntüle"
 echo ""
 echo "0-Programdan çıkış"
 echo ""
 echo -n "Seçiminizi giriniz: "
 read secilen
 echo ""
 case $secilen in
  1) uname ; projef ;;
  2) lscpu ; projef ;;
  3) lshw ; projef ;;
  4) hwinfo ; projef ;;
  5) lspci ; projef ;;
  6) lsscsi ; projef ;;
  7) mount | column -t ; projef ;;
  8) inxi -Fx ; projef ;;
  9) lsusb ; projef ;;
  0) exit ;;
  *) echo "Lütfen 1,2,3,4,5,6,7,8,9 ya da 0 değerini giriniz"; projef
  esac
  zenity --info --no-wrap --text="$secilen . seçeneği seçtiniz. Yeni bir seçim için "OK" seçeneğine tıklayınız."  \
  --width 400 \
  --height 200 \
  
done
